project:
  type: website

website:
  title: "Diabetes"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: sources.qmd
        text: Sources
      - about.qmd
      - icon: github
        href: https://github.com/
        aria-label: GitHub
      
      
format:
  html:
    theme: cosmo
    fontsize: 1.14em
    linestretch: 1.8
    css: styles.css
    toc: true



publish:
  provider: rpubs
  url: "https://vibhadara.quarto.pub/Diabetes/"